/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/availability": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description The raw set of bookable Slots (available and unbooked) within the Visitor
         *     horizon. The range is implied by the public caller.
         */
        get: operations["Public_getAvailability"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/booking-types": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description List active Booking Types. */
        get: operations["Public_listBookingTypes"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/bookings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * @description Create a Booking. The server verifies that `durationSlots` consecutive
         *     Slots from `startSlot` are all available and unbooked, and within the
         *     Visitor horizon. First valid request wins.
         */
        post: operations["Public_createBooking"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/host/availability": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description All Slots with their state within the Host horizon. */
        get: operations["HostApi_getHostAvailability"];
        /**
         * @description Bulk open/close Slots. Editing a `booked` Slot is rejected; the Host must
         *     cancel its Booking first.
         */
        put: operations["HostApi_editAvailability"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/host/booking-types": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description List all Booking Types (including inactive), for the Host Dashboard. */
        get: operations["HostApi_listAllBookingTypes"];
        put?: never;
        post: operations["HostApi_createBookingType"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/host/booking-types/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["HostApi_updateBookingType"];
        trace?: never;
    };
    "/api/host/booking-types/{slug}/activate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["HostApi_activateBookingType"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/host/booking-types/{slug}/deactivate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["HostApi_deactivateBookingType"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/host/bookings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description List scheduled Bookings. */
        get: operations["HostApi_listBookings"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/host/bookings/{id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * @description Cancel a Booking. Its Slots return to `available` so the Host can
         *     manage them immediately without manual re-opening.
         */
        post: operations["HostApi_cancelBooking"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * @description A bulk edit of the Host's availability. Each entry opens (`available`) or
         *     closes (`unavailable`) a Slot. A `booked` Slot cannot be edited here — the
         *     Host must cancel its Booking first.
         */
        AvailabilityEdit: {
            start: components["schemas"]["SlotStart"];
            /**
             * @description Target state: `available` to open, `unavailable` to close.
             * @enum {string}
             */
            state: "available" | "unavailable";
        };
        /** @description A Slot the Visitor may book: available and unbooked. */
        AvailableSlot: {
            start: components["schemas"]["SlotStart"];
        };
        /**
         * @description A concrete reservation a Visitor makes against a Booking Type at a specific
         *     date and time. Occupies `durationSlots` consecutive Slots from `startSlot`.
         */
        Booking: {
            /** @description `YYYY-MM-DD-HH-MM` of the start Slot (UTC). */
            id: components["schemas"]["BookingId"];
            bookingTypeSlug: components["schemas"]["Slug"];
            startSlot: components["schemas"]["SlotStart"];
            visitorName: string;
            /** Format: email */
            visitorEmail: string;
        };
        /**
         * @description Booking identifier derived from the start Slot, formatted `YYYY-MM-DD-HH-MM`
         *     in UTC (e.g. `2026-06-12-10-15`). A start Slot uniquely identifies a Booking.
         */
        BookingId: string;
        /**
         * @description A reusable template the Host defines, describing one kind of bookable meeting.
         *     Not tied to any specific date or time.
         * @example {
         *       "slug": "workshop",
         *       "title": "Workshop",
         *       "description": "A 90-minute hands-on workshop session.",
         *       "durationSlots": 6,
         *       "active": false
         *     }
         */
        BookingType: {
            /** @description URL-friendly slug. Unique and immutable; serves as the identifier. */
            slug: components["schemas"]["Slug"];
            title: string;
            description: string;
            /**
             * Format: int32
             * @description Duration in Slots (15 minutes each). Immutable once created.
             */
            durationSlots: number;
            /** @description Deactivated Booking Types are hidden from new Bookings but retained. */
            active: boolean;
        };
        /**
         * @description The requested Slots are no longer all available/unbooked (taken by another
         *     Booking, or closed by the Host). First valid request wins.
         */
        Conflict: {
            /** @enum {string} */
            code: "conflict";
            message: string;
        };
        CreateBooking: {
            bookingTypeSlug: components["schemas"]["Slug"];
            startSlot: components["schemas"]["SlotStart"];
            visitorName: string;
            /** Format: email */
            visitorEmail: string;
        };
        CreateBookingType: {
            slug: components["schemas"]["Slug"];
            title: string;
            description: string;
            /** Format: int32 */
            durationSlots: number;
        };
        /** @description A Slot with its full state, as seen by the Host. */
        HostSlot: {
            start: components["schemas"]["SlotStart"];
            state: components["schemas"]["SlotState"];
        };
        NotFound: {
            /** @enum {string} */
            code: "not_found";
            message: string;
        };
        /**
         * Format: date-time
         * @description The UTC start instant of a Slot, ISO 8601, aligned to a 15-minute boundary
         *     (e.g. `2026-06-12T10:15:00Z`).
         */
        SlotStart: string;
        /** @enum {string} */
        SlotState: "unavailable" | "available" | "booked";
        /** @description Booking Type identifier: a URL-friendly slug. Unique and immutable. */
        Slug: string;
        /**
         * @description Returned by Host-only endpoints when the Bearer token is missing or invalid.
         *     There is exactly one Host; Visitor endpoints are public.
         */
        Unauthorized: {
            /** @enum {string} */
            code: "unauthorized";
            message: string;
        };
        /** @description A rule violation: malformed request against the domain rules. */
        Unprocessable: {
            /** @enum {string} */
            code: "unprocessable";
            message: string;
        };
        /** @description Only title and description are editable; slug and duration are immutable. */
        UpdateBookingType: {
            title?: string;
            description?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    Public_getAvailability: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AvailableSlot"][];
                };
            };
        };
    };
    Public_listBookingTypes: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BookingType"][];
                };
            };
        };
    };
    Public_createBooking: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateBooking"];
            };
        };
        responses: {
            /** @description The request has succeeded and a new resource has been created as a result. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Booking"];
                };
            };
            /** @description The server cannot find the requested resource. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotFound"];
                };
            };
            /**
             * @description The requested Slots are no longer all available/unbooked (taken by another
             *     Booking, or closed by the Host). First valid request wins.
             */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Conflict"];
                };
            };
            /** @description A rule violation: malformed request against the domain rules. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Unprocessable"];
                };
            };
        };
    };
    HostApi_getHostAvailability: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HostSlot"][];
                };
            };
            /**
             * @description Returned by Host-only endpoints when the Bearer token is missing or invalid.
             *     There is exactly one Host; Visitor endpoints are public.
             */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Unauthorized"];
                };
            };
        };
    };
    HostApi_editAvailability: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AvailabilityEdit"][];
            };
        };
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HostSlot"][];
                };
            };
            /**
             * @description Returned by Host-only endpoints when the Bearer token is missing or invalid.
             *     There is exactly one Host; Visitor endpoints are public.
             */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Unauthorized"];
                };
            };
            /** @description A rule violation: malformed request against the domain rules. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Unprocessable"];
                };
            };
        };
    };
    HostApi_listAllBookingTypes: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BookingType"][];
                };
            };
            /**
             * @description Returned by Host-only endpoints when the Bearer token is missing or invalid.
             *     There is exactly one Host; Visitor endpoints are public.
             */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Unauthorized"];
                };
            };
        };
    };
    HostApi_createBookingType: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateBookingType"];
            };
        };
        responses: {
            /** @description The request has succeeded and a new resource has been created as a result. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BookingType"];
                };
            };
            /**
             * @description Returned by Host-only endpoints when the Bearer token is missing or invalid.
             *     There is exactly one Host; Visitor endpoints are public.
             */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Unauthorized"];
                };
            };
            /** @description A rule violation: malformed request against the domain rules. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Unprocessable"];
                };
            };
        };
    };
    HostApi_updateBookingType: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: components["schemas"]["Slug"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateBookingType"];
            };
        };
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BookingType"];
                };
            };
            /**
             * @description Returned by Host-only endpoints when the Bearer token is missing or invalid.
             *     There is exactly one Host; Visitor endpoints are public.
             */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Unauthorized"];
                };
            };
            /** @description The server cannot find the requested resource. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotFound"];
                };
            };
        };
    };
    HostApi_activateBookingType: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: components["schemas"]["Slug"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BookingType"];
                };
            };
            /**
             * @description Returned by Host-only endpoints when the Bearer token is missing or invalid.
             *     There is exactly one Host; Visitor endpoints are public.
             */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Unauthorized"];
                };
            };
            /** @description The server cannot find the requested resource. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotFound"];
                };
            };
        };
    };
    HostApi_deactivateBookingType: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: components["schemas"]["Slug"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BookingType"];
                };
            };
            /**
             * @description Returned by Host-only endpoints when the Bearer token is missing or invalid.
             *     There is exactly one Host; Visitor endpoints are public.
             */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Unauthorized"];
                };
            };
            /** @description The server cannot find the requested resource. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotFound"];
                };
            };
        };
    };
    HostApi_listBookings: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Booking"][];
                };
            };
            /**
             * @description Returned by Host-only endpoints when the Bearer token is missing or invalid.
             *     There is exactly one Host; Visitor endpoints are public.
             */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Unauthorized"];
                };
            };
        };
    };
    HostApi_cancelBooking: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["schemas"]["BookingId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description There is no content to send for this request, but the headers may be useful. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /**
             * @description Returned by Host-only endpoints when the Bearer token is missing or invalid.
             *     There is exactly one Host; Visitor endpoints are public.
             */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Unauthorized"];
                };
            };
            /** @description The server cannot find the requested resource. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotFound"];
                };
            };
        };
    };
}
